package com.lrhb.dataaccess.dao.system;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lrhb.dataaccess.model.system.SysAccessPermission;

public interface SysAccessPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCESS_PERMISSION_TEST
     *
     * @mbggenerated Mon Dec 04 11:17:43 CST 2017
     */
    int deleteByPrimaryKey(String id);

    int deleteByRequestUrl(@Param("requestUrl") String requestUrl);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCESS_PERMISSION_TEST
     *
     * @mbggenerated Mon Dec 04 11:17:43 CST 2017
     */
    int insert(SysAccessPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCESS_PERMISSION_TEST
     *
     * @mbggenerated Mon Dec 04 11:17:43 CST 2017
     */
    int insertSelective(SysAccessPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCESS_PERMISSION_TEST
     *
     * @mbggenerated Mon Dec 04 11:17:43 CST 2017
     */
    SysAccessPermission selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCESS_PERMISSION_TEST
     *
     * @mbggenerated Mon Dec 04 11:17:43 CST 2017
     */
    int updateByPrimaryKeySelective(SysAccessPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCESS_PERMISSION_TEST
     *
     * @mbggenerated Mon Dec 04 11:17:43 CST 2017
     */
    int updateByPrimaryKey(SysAccessPermission record);

    /**
     * 获取所有访问权限配置
     * */
    List<SysAccessPermission> selectAll();

    /**
     * 根据url获取记录
     * @param url 请求路径
     * */
    SysAccessPermission selectByUrl(@Param("url") String url);
}