package com.lrhb.dataaccess.dao.system;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lrhb.dataaccess.model.system.SysMenu;
import com.lrhb.service.beans.system.SysMenuExtend;

public interface SysMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_MENU_TEST
     *
     * @mbggenerated Wed Dec 06 18:29:05 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_MENU_TEST
     *
     * @mbggenerated Wed Dec 06 18:29:05 CST 2017
     */
    int insert(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_MENU_TEST
     *
     * @mbggenerated Wed Dec 06 18:29:05 CST 2017
     */
    int insertSelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_MENU_TEST
     *
     * @mbggenerated Wed Dec 06 18:29:05 CST 2017
     */
    SysMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_MENU_TEST
     *
     * @mbggenerated Wed Dec 06 18:29:05 CST 2017
     */
    int updateByPrimaryKeySelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_MENU_TEST
     *
     * @mbggenerated Wed Dec 06 18:29:05 CST 2017
     */
    int updateByPrimaryKey(SysMenu record);


    /**
     * 分页获取菜单
     * */
    List<SysMenuExtend> getAll(@Param("start") int start,
                                   @Param("end") int end,
                                   @Param("menuName") String menuName,
                                   @Param("menuCode") String menuCode,
                                   @Param("parentMenuId") String parentMenuId);

    /**
     * 获取菜单大小
     * */
    int countGetAll( @Param("menuName") String menuName,
                     @Param("menuCode") String menuCode,
                     @Param("parentMenuId") String parentMenuId);

    /**
     * 获取一级菜单列表
     * */
    List<SysMenu> getFirstClassMenus();

    /**
     * 根据菜单名称获取菜单
     * @param menuName 菜单名称
     */
    SysMenu getByMenuName(@Param("menuName") String menuName);

    /**
     * 获取一级菜单最大CODE
     * */
    String getMaxCodeOfFirstClass();

    /**
     * 获取二级菜单最大CODE
     * @param parentMenuId 父菜单id
     * */
    String getMaxCodeOfSecondClass(@Param("parentMenuId") String parentMenuId);

    /**
     * 获取子菜单个数
     * @param menuId 父菜单id
     * */
    int getChildrenCount(@Param("menuId") String menuId);

    /**
     * 根据主键获取菜单信息
     * @param id 菜单主键
     * */
    SysMenuExtend getById(@Param("id") String id);

    /**
     * 根据后台请求路径获取记录
     * @param requestUrl 后台请求路径
     * */
    SysMenu getByRequestUrl(@Param("requestUrl") String requestUrl);
}