package com.lrhb.dataaccess.dao.system;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lrhb.dataaccess.model.system.SysMenuRole;
import com.lrhb.dataaccess.model.system.SysMenu;

public interface SysMenuRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_MENU_ROLE_TEST
     *
     * @mbggenerated Wed Dec 06 18:29:27 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_MENU_ROLE_TEST
     *
     * @mbggenerated Wed Dec 06 18:29:27 CST 2017
     */
    int insert(SysMenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_MENU_ROLE_TEST
     *
     * @mbggenerated Wed Dec 06 18:29:27 CST 2017
     */
    int insertSelective(SysMenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_MENU_ROLE_TEST
     *
     * @mbggenerated Wed Dec 06 18:29:27 CST 2017
     */
    SysMenuRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_MENU_ROLE_TEST
     *
     * @mbggenerated Wed Dec 06 18:29:27 CST 2017
     */
    int updateByPrimaryKeySelective(SysMenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_MENU_ROLE_TEST
     *
     * @mbggenerated Wed Dec 06 18:29:27 CST 2017
     */
    int updateByPrimaryKey(SysMenuRole record);

    /**
     * 根据角色获取可见菜单列表
     * @param roleIds 角色id列表
     * */
    List<SysMenu> getDistinctMenusByRoleIds(List<String> roleIds);

    /**
     * 根据菜单id删除记录
     * @param menuId 菜单id
     */
    int deleteByMenuId(@Param("menuId") String menuId);

    /**
     * 根据菜单id和角色Id获取记录
     * @param menuId 菜单id
     * @param roleId 角色id
     * */
    SysMenuRole selectByMenuIdAndRoleId(@Param("menuId") String menuId,
                                            @Param("roleId") String roleId);

    /**
     * 获取菜单对应的角色id列表
     * @param menuId 菜单id
     * */
    List<String> getRoleIdsByMenuId(@Param("menuId") String menuId);
}