package com.lrhb.dataaccess.dao.system;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lrhb.dataaccess.model.system.SysOrganize;

public interface SysOrganizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORGANIZE_TEST
     *
     * @mbggenerated Thu Dec 07 15:21:02 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORGANIZE_TEST
     *
     * @mbggenerated Thu Dec 07 15:21:02 CST 2017
     */
    int insert(SysOrganize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORGANIZE_TEST
     *
     * @mbggenerated Thu Dec 07 15:21:02 CST 2017
     */
    int insertSelective(SysOrganize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORGANIZE_TEST
     *
     * @mbggenerated Thu Dec 07 15:21:02 CST 2017
     */
    SysOrganize selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORGANIZE_TEST
     *
     * @mbggenerated Thu Dec 07 15:21:02 CST 2017
     */
    int updateByPrimaryKeySelective(SysOrganize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORGANIZE_TEST
     *
     * @mbggenerated Thu Dec 07 15:21:02 CST 2017
     */
    int updateByPrimaryKey(SysOrganize record);


    /**
     * 获取所有组织机构
     * */
    List<SysOrganize> getAll();

    /**
     * 获取子机构个数
     * @param parentId 父机构id
     * */
    int countChildren(@Param("parentId") String parentId);

    /**
     * 根据名称获取组织机构
     * @param orgName 组织机构名称
     * */
    SysOrganize getByName(@Param("orgName") String orgName);

    /**
     * 获取根组织机构
     * */
    SysOrganize getRoot();

    /**
     * 找到某一层机构最大序号
     * @param level 机构层级
     * */
    String getMaxOrgCode(@Param("level") int level);
}