package com.lrhb.dataaccess.dao.system;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lrhb.dataaccess.model.system.SysRole;

public interface SysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_TEST
     *
     * @mbggenerated Mon Dec 04 11:17:05 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_TEST
     *
     * @mbggenerated Mon Dec 04 11:17:05 CST 2017
     */
    int insert(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_TEST
     *
     * @mbggenerated Mon Dec 04 11:17:05 CST 2017
     */
    int insertSelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_TEST
     *
     * @mbggenerated Mon Dec 04 11:17:05 CST 2017
     */
    SysRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_TEST
     *
     * @mbggenerated Mon Dec 04 11:17:05 CST 2017
     */
    int updateByPrimaryKeySelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_TEST
     *
     * @mbggenerated Mon Dec 04 11:17:05 CST 2017
     */
    int updateByPrimaryKey(SysRole record);

    /**
     * 获取所有角色
     * @param start 开始
     * @param end 结束
     * */
    List<SysRole> selectAll(
            @Param("start") int start,
            @Param("end") int end,
            @Param("roleName") String roleName,
            @Param("isSuper") String isSuper);


    /**
     * 获取所有角色个数
     * */
    int countGetAll( @Param("roleName") String roleName,
                     @Param("isSuper") String isSuper);

    /**
     * 根据角色名称获取记录
     * @param roleName 角色名称
     * */
    SysRole getByRoleName(@Param("roleName") String roleName);

    /**
     * 根据id获取角色列表
     * @param ids id列表
     * */
    List<String> getRoleNamesByIds(@Param("ids") List<String> ids);
}