package com.lrhb.dataaccess.dao.system;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lrhb.dataaccess.model.system.SysRole;
import com.lrhb.dataaccess.model.system.SysUserRole;

public interface SysUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER_ROLE_TEST
     *
     * @mbggenerated Mon Dec 04 14:08:33 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER_ROLE_TEST
     *
     * @mbggenerated Mon Dec 04 14:08:33 CST 2017
     */
    int insert(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER_ROLE_TEST
     *
     * @mbggenerated Mon Dec 04 14:08:33 CST 2017
     */
    int insertSelective(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER_ROLE_TEST
     *
     * @mbggenerated Mon Dec 04 14:08:33 CST 2017
     */
    SysUserRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER_ROLE_TEST
     *
     * @mbggenerated Mon Dec 04 14:08:33 CST 2017
     */
    int updateByPrimaryKeySelective(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER_ROLE_TEST
     *
     * @mbggenerated Mon Dec 04 14:08:33 CST 2017
     */
    int updateByPrimaryKey(SysUserRole record);

    /**
     * 根据用户id获取角色列表
     * @param userId 用户id
     * */
    List<String> getRoleNamesByUserId(@Param("userId") String userId);

    /**
     * 根据用户id获取角色列表
     * @param userId 用户id
     * */
    List<SysRole> getRolesByUserId(@Param("userId") String userId);

    /**
     * 根据角色id获取用户数
     * @param roleId 角色id
     * */
    int countByRoleId(@Param("roleId") String roleId);

    /**
     * 批量插入
     * @param list 记录列表
     * */
    int batchInsert(@Param("list") List<SysUserRole> list);

    /**
     * 根据用户id删除
     * @param userId 用户id
     * */
    int deleteByUserId(@Param("userId") String userId);
}